// Auto generated by env plugin. DO NOT EDIT.
type Env = {
  PUBLIC_API_PRIVATE_KEY: string;
  API_STOP_ARRIVE_URL: string;
  API_BUS_ROUTE_URL: string;
  API_BUS_LOCATION_URL: string;
  API_STOP_URL: string;
};

interface ImportMeta {
  readonly env: Env & {};
}
